name: Poranny Budzik Aplikacji

on:
  schedule:
    # cron: 'MINUTY GODZINY * * DNI_TYGODNIA' 
    # Uruchamia o 5:00 UTC (czyli 6:00 lub 7:00 w Polsce) od poniedziałku (1) do piątku (5)
    - cron: '0 1 * * 1-5'
  workflow_dispatch: # Pozwala odpalić ręcznie z panelu

jobs:
  run-budzik:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v3

      - name: Skonfiguruj Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zainstaluj biblioteki
        run: |
          pip install playwright
          playwright install chromium

      - name: Odpal budzik
        run: python wakeup_caller.py
